name: labwork1

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build_and_test:
    name: Сборка и тестирование
    runs-on: ubuntu-latest

    steps:
      # 1. Установка зависимостей
      - name: Установка инструментов
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          build-essential \
            
      # 2. Получение кода
      - name: Получение кода
        uses: actions/checkout@v4

      # 3. Сборка main
      - name: Сборка labwork1
        run: make

      # 4. запуск main
      - name: запуск
        run: ./labwork1
      
      # 5. make cleanall
      - name: clean all
        run: make cleanall
