name: labwork1

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build_test_lint:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
      # 1. Install dependencies
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y\
           build-essential\
           clang-tidy\
           libgtest-dev


      # 2. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. Linting with clang-tidy
      - name: Run clang-tidy linter
        run: |
          find . -name '*.cpp' | xargs -I{} clang-tidy {} -- -std=c++17

      # 4. Build main with make
      - name: Build labwork1
        run: make

      # 5. Run the program
      - name: Run program
        run: ./labwork1
        
      # 6. Build tests
      - name: Build tests
        run: make tests
        
      # 7. Run tests
      - name: run tests
        run: ./tests

      # 7. Clean build files
      - name: Clean all
        run: make cleanall

